### ISSUE TITLE
Double the Donation settings should be reviewed

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/give-double-the-donation#2]
## Details

The Double the Donation settings page should follow the standards set by existing GiveWP plugins so that it is more discoverable and maintainable.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/97235020-602e4b00-17b8-11eb-9078-d4cde7dfe7e2.png)

1. The `Double the Donation` tab is nested under `General > Settings`, but other add-ons have top-level tabs. It's unclear to me whether this is intentional or not.
2. This registration form link should probably use a short URL in case we need to update it in the future.
3. This docs URL does not exist

## Acceptance Criteria

-   [x] The settings tab position is reviewed and moved if necessary.
-   [x] The registration form link uses a short URL.
-   [x] The docs URL in the bottom right corner of the settings page is fixed.

**Comment by mathetos** [comment]
1. The settings should be on its own Tab -- that's expected behavior for all GiveWP addons so we should conform to that
2. That should be a docs link, agreed. I can take care of that
3. That will most likely go to our Announcement article or to the WordPress.org readme to the FAQ section. I think it's important that there is somewhere to point users to no matter what, but our FREE add-ons don't typically have online docs on givewp.com so we'll get a little creative here.
